# File: requests.http
@payment_id =f12d163e-948a-4ca4-9a1b-919ffaed4eb6
@reservation_id = f12d163e-948a-4ca4-9a1b-919ffaed4eb6
@access_token = 
# @name HealthCheck
GET http://localhost:8080/health

###
# @name Login Success
# Tenta fazer login com credenciais válidas.
# Deverá retornar um access_token.
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

###
# @name Get Availability
# Consulta a disponibilidade de ingressos para um evento. (Rota pública)
GET http://localhost:8080/api/v1/events/event-123/availability

###
# @name Create Reservation Success
# Tenta criar uma reserva para um ingresso. Requer token de autenticação.
# ANTES DE EXECUTAR: Faça o login, copie o access_token e cole abaixo.
POST http://localhost:8080/api/v1/reservations
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "event_id": "event-123",
  "ticket_type_id": "ticket-type-standard",
  "quantity": 2
}

###
# @name Create Reservation No Auth
# Tenta criar uma reserva sem o token. Deve falhar com 401.
POST http://localhost:8080/api/v1/reservations
Content-Type: application/json

{
  "event_id": "event-123",
  "ticket_type_id": "ticket-type-standard",
  "quantity": 1
}

###
# @name Create Reservation No Stock
# Tenta criar uma reserva para mais ingressos do que o disponível. Deve falhar com 409.
# ANTES DE EXECUTAR: Faça o login, copie o access_token e cole abaixo.
POST http://localhost:8080/api/v1/reservations
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "event_id": "event-123",
  "ticket_type_id": "ticket-type-vip",
  "quantity": 999
}

###
# @name Payment Webhook Simulation (APPROVED)
# Simula a notificação do gateway de que um pagamento foi aprovado.
POST http://localhost:8080/api/v1/payments/webhook
Content-Type: application/json

{
  "payment_id": "{{payment_id}}",
  "reservation_id": "{{reservation_id}}",
  "status": "APPROVED",
  "amount": 100.00
}


###
# @name Payment Webhook Simulation (REJECTED)
# Simula a notificação do gateway de que um pagamento foi rejeitado.
POST http://localhost:8080/api/v1/payments/webhook
Content-Type: application/json

{
  "payment_id": "pay_another_reservation_id",
  "reservation_id": "another_reservation_id",
  "status": "REJECTED",
  "amount": 50.00
}